//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTasks()
        {
            this.tbUsers = new HashSet<tbUsers>();
        }
    
        public int TaskId { get; set; }
        public string Title { get; set; }
        public short Priority { get; set; }
        public short Status { get; set; }
        public string Details { get; set; }
        public System.DateTime ToDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsers> tbUsers { get; set; }
    }
}
